version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - 11211:11211

volumes:
  mongodb-data: {}