site_name: Hyprxa
site_description: An asynchronous data integration framework and event hub built on FastAPI.

theme:
  name: material
  palette:
      - scheme: 'default'
        media: '(prefers-color-scheme: light)'
        toggle:
          icon: 'material/lightbulb'
          name: "Switch to dark mode"
      - scheme: 'slate'
        media: '(prefers-color-scheme: dark)'
        primary: 'blue'
        toggle:
          icon: 'material/lightbulb-outline'
          name: 'Switch to light mode'
  features:
      - navigation.sections

repo_name: newvicx/hyprxa
repo_url: https://github.com/newvicx/hyprxa/
edit_uri: ""


markdown_extensions:
  - admonition
  - codehilite:
      css_class: highlight
  - mkautodoc

extra_css:
    - css/custom.css